# Generated by Django 5.2.8 on 2026-04-09 23:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_adminwalletlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("PAYOUT", "Payout"),
                    ("CHARGE", "Charge"),
                    ("REFUND", "Refund"),
                    ("FUNDING", "Funding"),
                    ("WITHDRAWAL", "Withdrawal"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="EmbedlyWallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("wallet_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "account_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("bank_name", models.CharField(blank=True, max_length=255, null=True)),
                ("bank_code", models.CharField(blank=True, max_length=50, null=True)),
                ("provider", models.CharField(default="EMBEDLY", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedly_wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
