# Generated by Django 5.1.4 on 2025-12-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("SHIFT_POSTED", "Shift Posted"),
                    ("SHIFT_APPROVED", "Shift Approved"),
                    ("REMINDER", "Reminder"),
                    ("CANCELLED", "Shift Cancelled"),
                    ("BOOKED", "Shift Booked"),
                    ("MESSAGE", "New Message"),
                    ("INVOICE_UPCOMING", "Invoice Upcoming"),
                    ("INVOICE_GENERATED", "Invoice Generated"),
                    ("BROADCAST", "Broadcast"),
                ],
                max_length=50,
            ),
        ),
    ]
