"""
Django settings for shifta_project project.

Generated by 'django-admin startproject' using Django 5.1.4.
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-t7i^fltw=fd6=sq4%$c+)2d8_=bst-m4-n15#^#4w9^v9-^6%5"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["http://qwikshifthealth.com", "https://shifta-frontend.vercel.app", "localhost", "127.0.0.1", "172.203.248.172"]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://172.203.248.172:3000",
    "http://qwikshifthealth.com:3000",
    "https://shifta-frontend.vercel.app"
]

CSRF_TRUSTED_ORIGINS = [
    "https://http://qwikshifthealth.com/",
    "http://172.203.248.172:8000",
    "http://qwikshifthealth.com:3000",
    "https://shifta-frontend.vercel.app/"
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
    # Third-party apps
    "rest_framework",
    "rest_framework.authtoken",
    "drf_spectacular",
    "django_filters",
    "channels",
    "corsheaders",
    
    # Local apps
    "core",
    "accounts",
    "shifts",
    "billing",
    "communications",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "shifta_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "shifta_project.wsgi.application"
ASGI_APPLICATION = "shifta_project.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DB_NAME"),
        "USER": os.environ.get("DB_USER"),
        "PASSWORD": os.environ.get("DB_PASSWORD"),
        "HOST": os.environ.get("DB_HOST"),
        "PORT": os.environ.get("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# DRF Settings
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_RENDERER_CLASSES": (
        "core.renderers.StandardResponseRenderer",
        "rest_framework.renderers.JSONRenderer",
    ),
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "EXCEPTION_HANDLER": "core.exceptions.custom_exception_handler",
}

# Swagger Settings
SPECTACULAR_SETTINGS = {
    "TITLE": "Shifta API",
    "DESCRIPTION": "On-Demand Healthcare Staffing API",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

# Celery Settings
CELERY_BROKER_URL = "redis://localhost:6379/0"
CELERY_RESULT_BACKEND = "redis://localhost:6379/0"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"

# Celery Beat - periodic tasks
CELERY_BEAT_SCHEDULE = {
    "close-expired-open-shifts": {
        "task": "shifts.tasks.close_expired_open_shifts",
        "schedule": 60 * 60,  # Run every hour
    },
}

# Custom User Model
AUTH_USER_MODEL = "accounts.User"

# Embedly Wallet Settings
EMBEDLY_CURRENCY_ID = os.environ.get("EMBEDLY_CURRENCY_ID")
EMBEDLY_API_KEY = os.environ.get("EMBEDLY_API_KEY")
EMBEDLY_BASE_URL = os.environ.get("EMBEDLY_BASE_URL")
EMBEDLY_PAYOUT_URL = os.environ.get("EMBEDLY_PAYOUT_URL")
EMBEDLY_COUNTRY_ID = os.environ.get("EMBEDLY_COUNTRY_ID")
EMBEDLY_ORGANISATION_ID = os.environ.get("EMBEDLY_ORGANISATION_ID")
EMBEDLY_CUSTOMER_TYPE_ID = os.environ.get("EMBEDLY_CUSTOMER_TYPE_ID")
EMBEDLY_DEFAULT_WALLET_ACCOUNT_NUMBER = os.environ.get("EMBEDLY_DEFAULT_WALLET_ACCOUNT_NUMBER")
DEFAULT_WALLET_TYPE = os.environ.get("DEFAULT_WALLET_TYPE", "EMBEDLY")

# Paystack Settings
PAYSTACK_SECRET_KEY = os.environ.get("PAYSTACK_SECRET_KEY")
PAYSTACK_PUBLIC_KEY = os.environ.get("PAYSTACK_PUBLIC_KEY")
PAYSTACK_CALLBACK_URL = os.environ.get("PAYSTACK_CALLBACK_URL", "")
