# Generated by Django 5.1.4 on 2025-12-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_waitlistprofessional_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="waitlistprofessional",
            name="shift_rate_12hr",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="waitlistprofessional",
            name="shift_rate_16hr",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="waitlistprofessional",
            name="shift_rate_24hr",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
