# Generated by Django 5.2.8 on 2026-04-10 06:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_waitlistprofessional_shift_rate_12hr_and_more"),
        ("shifts", "0005_shiftapplication_cancellation_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="professional",
            name="avg_rating",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name="professional",
            name="total_cancelled_shifts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="professional",
            name="total_completed_shifts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="professional",
            name="total_ratings",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="review",
            name="is_auto",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="review",
            name="shift_application",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review",
                to="shifts.shiftapplication",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                condition=models.Q(("shift_application__isnull", False)),
                fields=("shift_application",),
                name="unique_review_per_application",
            ),
        ),
    ]
