# Generated by Django 5.2.8 on 2026-04-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0003_extratimerequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftapplication",
            name="check_in_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="shiftapplication",
            name="check_out_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
