# Generated by Django 5.2.8 on 2026-04-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0004_shiftapplication_check_in_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftapplication",
            name="cancellation_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="shiftapplication",
            name="cancelled_by",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
